In [1]:
!pip install -q transformers==4.40.2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.0/138.0 kB 7.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.0/9.0 MB 100.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 30.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 101.2 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sentence-transformers 5.2.0 requires transformers<6.0.0,>=4.41.0, but you have transformers 4.40.2 which is incompatible.

In [2]:
import os
import pandas as pd

BASE_PATH = "/kaggle/input/crisismmd"
ANNOTATION_PATH = os.path.join(BASE_PATH, "annotations")

all_data = []

for file in os.listdir(ANNOTATION_PATH):
    if file.endswith(".tsv"):
        
        disaster_type = file.replace("_final_data.tsv", "")
        file_path = os.path.join(ANNOTATION_PATH, file)
        
        df = pd.read_csv(file_path, sep="\t")
        df["disaster_type"] = disaster_type
        
        all_data.append(df)

# Combine all events
data = pd.concat(all_data, ignore_index=True)

print("Total samples:", len(data))
print("Columns:", data.columns)
data.head()

Total samples: 18126
Columns: Index(['tweet_id', 'image_id', 'text_info', 'text_info_conf', 'image_info',
       'image_info_conf', 'text_human', 'text_human_conf', 'image_human',
       'image_human_conf', 'image_damage', 'image_damage_conf', 'tweet_text',
       'image_url', 'image_path', 'disaster_type'],
      dtype='object')

,tweet_id,image_id,text_info,text_info_conf,image_info,image_info_conf,text_human,text_human_conf,image_human,image_human_conf,image_damage,image_damage_conf,tweet_text,image_url,image_path,disaster_type
0,917791044158185473,917791044158185473_0,informative,1.0000,informative,0.6766,other_relevant_information,1.0000,other_relevant_information,0.6766,NaN,NaN,RT @Gizmodo: Wildfires raging through Northern...,http://pbs.twimg.com/media/DLyi_WYVYAApwNg.jpg,data_image/california_wildfires/10_10_2017/917...,california_wildfires
1,917791130590183424,917791130590183424_0,informative,1.0000,informative,0.6667,infrastructure_and_utility_damage,1.0000,affected_individuals,0.6667,NaN,NaN,PHOTOS: Deadly wildfires rage in California ht...,http://pbs.twimg.com/media/DLymKm9UMAAu0qw.jpg,data_image/california_wildfires/10_10_2017/917...,california_wildfires
2,917791291823591425,917791291823591425_0,informative,0.6813,informative,1.0000,other_relevant_information,0.6813,infrastructure_and_utility_damage,1.0000,severe_damage,1.0,RT @Cal_OES: PLS SHARE: Weâ€™re capturing wild...,http://pbs.twimg.com/media/DLudaaZV4AAjT7x.jpg,data_image/california_wildfires/10_10_2017/917...,california_wildfires
3,917791291823591425,917791291823591425_1,informative,0.6813,not_informative,1.0000,other_relevant_information,0.6813,not_relevant_or_cant_judge,1.0000,NaN,NaN,RT @Cal_OES: PLS SHARE: Weâ€™re capturing wild...,http://pbs.twimg.com/media/DLudaZXUMAABAEZ.jpg,data_image/california_wildfires/10_10_2017/917...,california_wildfires
4,917792092100988929,917792092100988929_0,informative,0.6727,informative,0.6612,other_relevant_information,0.6727,infrastructure_and_utility_damage,0.6612,severe_damage,1.0,RT @TIME: California's raging wildfires as you...,http://pbs.twimg.com/media/DLwNe-NXUAE0XCw.jpg,data_image/california_wildfires/10_10_2017/917...,california_wildfires

In [3]:
print(data.columns)

Index(['tweet_id', 'image_id', 'text_info', 'text_info_conf', 'image_info',
       'image_info_conf', 'text_human', 'text_human_conf', 'image_human',
       'image_human_conf', 'image_damage', 'image_damage_conf', 'tweet_text',
       'image_url', 'image_path', 'disaster_type'],
      dtype='object')

In [4]:
def simplify_label(name):
    if "flood" in name:
        return "Flood"
    elif "wildfire" in name:
        return "Fire"
    elif "earthquake" in name:
        return "Earthquake"
    elif "hurricane" in name:
        return "Hurricane"
    else:
        return "Other"

data["label"] = data["disaster_type"].apply(simplify_label)

print(data["label"].value_counts())

label
Hurricane     13530
Earthquake     1982
Fire           1589
Flood          1025
Name: count, dtype: int64

In [5]:
data_raw=data

In [6]:
data=data_raw

In [7]:
BASE_PATH = "/kaggle/input/crisismmd"

data["image_full_path"] = data["image_path"].apply(
    lambda x: os.path.join(BASE_PATH, x)
)

# data["image_full_path"].head()

In [8]:
data.head()

,tweet_id,image_id,text_info,text_info_conf,image_info,image_info_conf,text_human,text_human_conf,image_human,image_human_conf,image_damage,image_damage_conf,tweet_text,image_url,image_path,disaster_type,label,image_full_path
0,917791044158185473,917791044158185473_0,informative,1.0000,informative,0.6766,other_relevant_information,1.0000,other_relevant_information,0.6766,NaN,NaN,RT @Gizmodo: Wildfires raging through Northern...,http://pbs.twimg.com/media/DLyi_WYVYAApwNg.jpg,data_image/california_wildfires/10_10_2017/917...,california_wildfires,Fire,/kaggle/input/crisismmd/data_image/california_...
1,917791130590183424,917791130590183424_0,informative,1.0000,informative,0.6667,infrastructure_and_utility_damage,1.0000,affected_individuals,0.6667,NaN,NaN,PHOTOS: Deadly wildfires rage in California ht...,http://pbs.twimg.com/media/DLymKm9UMAAu0qw.jpg,data_image/california_wildfires/10_10_2017/917...,california_wildfires,Fire,/kaggle/input/crisismmd/data_image/california_...
2,917791291823591425,917791291823591425_0,informative,0.6813,informative,1.0000,other_relevant_information,0.6813,infrastructure_and_utility_damage,1.0000,severe_damage,1.0,RT @Cal_OES: PLS SHARE: Weâ€™re capturing wild...,http://pbs.twimg.com/media/DLudaaZV4AAjT7x.jpg,data_image/california_wildfires/10_10_2017/917...,california_wildfires,Fire,/kaggle/input/crisismmd/data_image/california_...
3,917791291823591425,917791291823591425_1,informative,0.6813,not_informative,1.0000,other_relevant_information,0.6813,not_relevant_or_cant_judge,1.0000,NaN,NaN,RT @Cal_OES: PLS SHARE: Weâ€™re capturing wild...,http://pbs.twimg.com/media/DLudaZXUMAABAEZ.jpg,data_image/california_wildfires/10_10_2017/917...,california_wildfires,Fire,/kaggle/input/crisismmd/data_image/california_...
4,917792092100988929,917792092100988929_0,informative,0.6727,informative,0.6612,other_relevant_information,0.6727,infrastructure_and_utility_damage,0.6612,severe_damage,1.0,RT @TIME: California's raging wildfires as you...,http://pbs.twimg.com/media/DLwNe-NXUAE0XCw.jpg,data_image/california_wildfires/10_10_2017/917...,california_wildfires,Fire,/kaggle/input/crisismmd/data_image/california_...

In [9]:
data.shape

(18126, 18)

In [10]:
data.columns

Index(['tweet_id', 'image_id', 'text_info', 'text_info_conf', 'image_info',
       'image_info_conf', 'text_human', 'text_human_conf', 'image_human',
       'image_human_conf', 'image_damage', 'image_damage_conf', 'tweet_text',
       'image_url', 'image_path', 'disaster_type', 'label', 'image_full_path'],
      dtype='object')

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18126 entries, 0 to 18125
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   tweet_id           18126 non-null  int64
 1   image_id           18126 non-null  object
 2   text_info          18126 non-null  object
 3   text_info_conf     18126 non-null  float64
 4   image_info         18126 non-null  object
 5   image_info_conf    18126 non-null  float64
 6   text_human         13807 non-null  object
 7   text_human_conf    13807 non-null  float64
 8   image_human        13807 non-null  object
 9   image_human_conf   13807 non-null  float64
 10  image_damage       3635 non-null   object
 11  image_damage_conf  3635 non-null   float64
 12  tweet_text         18126 non-null  object
 13  image_url          18126 non-null  object
 14  image_path         18126 non-null  object
 15  disaster_type      18126 non-null  object
 16  label              18126 non-null  object
 17  image_full_path    18126 non-null  object
dtypes: float64(5), int64(1), object(12)
memory usage: 2.5+ MB

In [12]:
print("Final dataset size:", len(data))

Final dataset size: 18126

In [13]:
final_data=data[['tweet_text','image_full_path','label']]

In [14]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

final_data["label_id"] = label_encoder.fit_transform(final_data["label"])

NUM_CLASSES = len(label_encoder.classes_)

print("Classes:", label_encoder.classes_)

Classes: ['Earthquake' 'Fire' 'Flood' 'Hurricane']

/tmp/ipykernel_24/1548387935.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_data["label_id"] = label_encoder.fit_transform(final_data["label"])

In [15]:
from sklearn.model_selection import train_test_split

train_df, val_df = train_test_split(
    final_data,
    test_size=0.2,
    stratify=final_data["label_id"],
    random_state=42
)

print("Train:", len(train_df))
print("Validation:", len(val_df))

Train: 14500
Validation: 3626

## Model training

In [16]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

import pandas as pd
import numpy as np
from PIL import Image

from transformers import AutoTokenizer, AutoModel
from torchvision import models, transforms
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [17]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda

In [18]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
MAX_LEN = 128

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [19]:
image_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
])

In [20]:
class CrisisDataset(Dataset):
    def __init__(self, df):
        self.df = df.reset_index(drop=True)

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]

        # Text
        encoding = tokenizer(
            row["tweet_text"],
            truncation=True,
            padding="max_length",
            max_length=MAX_LEN,
            return_tensors="pt"
        )

        input_ids = encoding["input_ids"].squeeze(0)
        attention_mask = encoding["attention_mask"].squeeze(0)

        # Image
        image = Image.open(row["image_full_path"]).convert("RGB")
        image = image_transform(image)

        label = torch.tensor(row["label_id"], dtype=torch.long)

        return {
            "input_ids": input_ids,
            "attention_mask": attention_mask,
            "image": image,
            "label": label
        }

In [21]:
train_dataset = CrisisDataset(train_df)
val_dataset = CrisisDataset(val_df)

train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=8)

In [22]:
class MultiModalModel(nn.Module):
    def __init__(self, num_classes):
        super(MultiModalModel, self).__init__()

        # BERT
        self.bert = AutoModel.from_pretrained("bert-base-uncased")

        # ResNet
        self.cnn = models.resnet50(pretrained=True)
        self.cnn.fc = nn.Identity()  # remove classifier

        # Fusion layers
        self.fc1 = nn.Linear(768 + 2048, 512)
        self.dropout = nn.Dropout(0.3)
        self.fc2 = nn.Linear(512, num_classes)

    def forward(self, input_ids, attention_mask, image):
        # Text
        bert_outputs = self.bert(
            input_ids=input_ids,
            attention_mask=attention_mask
        )
        text_features = bert_outputs.last_hidden_state[:, 0, :]  # CLS

        # Image
        image_features = self.cnn(image)

        # Fusion
        combined = torch.cat((text_features, image_features), dim=1)

        x = self.fc1(combined)
        x = torch.relu(x)
        x = self.dropout(x)
        x = self.fc2(x)

        return x

In [23]:
model = MultiModalModel(NUM_CLASSES).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=2e-5)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)

Downloading: "https://download.pytorch.org/models/resnet50-0676ba61.pth" to /root/.cache/torch/hub/checkpoints/resnet50-0676ba61.pth

100%|██████████| 97.8M/97.8M [00:00<00:00, 243MB/s]

In [24]:
from tqdm import tqdm

In [25]:
EPOCHS = 3

for epoch in range(EPOCHS):
    model.train()
    total_loss = 0
    correct = 0
    total = 0

    progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}")

    for batch in progress_bar:

        optimizer.zero_grad()

        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        images = batch["image"].to(device)
        labels = batch["label"].to(device)

        outputs = model(input_ids, attention_mask, images)

        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

        preds = torch.argmax(outputs, dim=1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)

        # Update tqdm bar
        progress_bar.set_postfix({
            "Loss": f"{loss.item():.4f}",
            "Acc": f"{correct/total:.4f}"
        })

    print(f"\nEpoch {epoch+1} Summary:")
    print(f"Avg Loss: {total_loss/len(train_loader):.4f}")
    print(f"Train Accuracy: {correct/total:.4f}")

Epoch 1:  55%|█████▍    | 997/1813 [05:01<03:53,  3.49it/s, Loss=0.0029, Acc=0.9674]/usr/local/lib/python3.12/dist-packages/PIL/Image.py:1047: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(
Epoch 1: 100%|██████████| 1813/1813 [09:11<00:00,  3.29it/s, Loss=0.0013, Acc=0.9770]

Epoch 1 Summary:
Avg Loss: 0.0853
Train Accuracy: 0.9770

Epoch 2: 100%|██████████| 1813/1813 [07:14<00:00,  4.17it/s, Loss=0.0008, Acc=0.9932]

Epoch 2 Summary:
Avg Loss: 0.0229
Train Accuracy: 0.9932

Epoch 3: 100%|██████████| 1813/1813 [07:11<00:00,  4.20it/s, Loss=0.0002, Acc=0.9952]

Epoch 3 Summary:
Avg Loss: 0.0159
Train Accuracy: 0.9952

In [26]:
model.eval()
correct = 0
total = 0

with torch.no_grad():
    for batch in val_loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        images = batch["image"].to(device)
        labels = batch["label"].to(device)

        outputs = model(input_ids, attention_mask, images)
        preds = torch.argmax(outputs, dim=1)

        correct += (preds == labels).sum().item()
        total += labels.size(0)

print("Validation Accuracy:", correct / total)

Validation Accuracy: 0.9867622724765582

In [27]:
import torch
import torch.nn.functional as F
from PIL import Image

def predict_single(text, image_path):

    model.eval()

    # ---- TEXT ----
    encoding = tokenizer(
        text,
        truncation=True,
        padding="max_length",
        max_length=MAX_LEN,
        return_tensors="pt"
    )

    input_ids = encoding["input_ids"].to(device)
    attention_mask = encoding["attention_mask"].to(device)

    # ---- IMAGE ----
    image = Image.open(image_path).convert("RGB")
    image = image_transform(image).unsqueeze(0).to(device)

    # ---- MODEL ----
    with torch.no_grad():
        outputs = model(input_ids, attention_mask, image)

        probs = F.softmax(outputs, dim=1)
        confidence, pred_class = torch.max(probs, dim=1)

    predicted_label = label_encoder.inverse_transform(
        [pred_class.item()]
    )[0]

    return {
        "prediction": predicted_label,
        "confidence": float(confidence.item())
    }

In [28]:
from transformers import pipeline

2026-02-28 07:08:29.683427: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1772262510.061782      24 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772262510.170759      24 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1772262511.062464      24 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772262511.062499      24 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772262511.062502      24 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772262511.062505      24 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

In [29]:
import re

def preprocess_for_ner(text):
    # Remove URLs
    text = re.sub(r"http\S+", "", text)

    # Remove mentions
    text = re.sub(r"@\w+", "", text)

    # Split hashtags properly
    text = re.sub(r"#", "", text)

    # Normalize capitalization (important!)
    text = text.title()

    return text.strip()

In [30]:
ner_pipeline = pipeline(
    "ner",
    model="Davlan/xlm-roberta-base-ner-hrl",
    aggregation_strategy="simple"
)

def extract_location(text):
    clean_text = preprocess_for_ner(text)
    entities = ner_pipeline(clean_text)
    locations = [
        ent["word"]
        for ent in entities
        if ent["entity_group"] in ["LOC", "GPE"]
    ]

    return locations

config.json:   0%|          | 0.00/980 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/211 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

In [31]:
def predict_with_location(text, image_path):
    
    disaster_result = predict_single(text, image_path)
    
    locations = extract_location(text)
    
    return {
        "disaster_type": disaster_result["prediction"],
        "confidence": disaster_result["confidence"],
        "locations_detected": locations if locations!=[] else "Unknown"
    }

In [32]:
random_index = np.random.randint(0, len(val_df))

sample = val_df.iloc[random_index]

result = predict_with_location(
    sample["tweet_text"],
    sample["image_full_path"]
)

print("Tweet:", sample["tweet_text"])
print("True Label:", label_encoder.inverse_transform([sample["label_id"]])[0])
print("Prediction:", result)

Tweet: Terrifying Video Shows Hurricane Irma Blasting St. Martin With 185 MPH Winds via Digg https://t.co/lqNMWfmaDL https://t.co/irZuDoxDeo
True Label: Hurricane
Prediction: {'disaster_type': 'Hurricane', 'confidence': 0.9999024868011475, 'locations_detected': ['St. Martin']}

In [33]:
torch.save(model.state_dict(), "multimodal_model_final.pt")

In [34]:
import pickle

with open("label_encoder.pkl", "wb") as f:
    pickle.dump(label_encoder, f)

In [35]:
# print(torch.__version__)

In [36]:
# !pip freeze